### ISSUE TITLE
Add more questions in quiz 

### ISSUE THREAD

**Issue by Suryansh1720001** [Suryansh1720001/Flag-Quiz#2]

**Comment by Arpit4u** [comment]
can I do it :)

**Comment by Suryansh1720001** [comment]
Hello @Arpit4u , 
Now you can work on it.
Thank You

**Comment by kaal-coder** [comment]
@Suryansh1720001 can you assign this to me too.

**Comment by ayushtiwari110** [comment]
Can u assign this to me, i will see if i can help...

**Comment by yukthapriya** [comment]
Can you assign the issue to me

**Comment by yukthapriya** [comment]
Can you assign this issue to me

**Comment by dasashreeya** [comment]
Hello, can I work on this?

**Comment by Yugal41735** [comment]
@Suryansh1720001  is this issue still open?

**Comment by Suryansh1720001** [comment]
@Yugal41735 
Yes, this is an open issue.
Do you want to resolve it?

**Comment by Yugal41735** [comment]
> @Yugal41735 Yes, this is an open issue. Do you want to resolve it?
Yup

**Comment by Yugal41735** [comment]
> @Yugal41735 Yes, this is an open issue. Do you want to resolve it?

Yup, And like how many ques can I add?

**Comment by Suryansh1720001** [comment]
@Yugal41735 
Not more than 5

**Comment by Rohit-554** [comment]
Hi @Suryansh1720001 Why to add so many questions we can use the quiz api that automatically provides the bunch of questions and that will be better,

**Comment by Suryansh1720001** [comment]
Yes, you are right @Rohit-554, but I want to make it offline so I added questions like this. 
Now in this project, more than 100 questions are available so I closed this issue. And if you want to collaborate on this project then you will collaborate according to your issue.
Thank you
