### ISSUE TITLE
Readme Correction

### ISSUE THREAD

**Issue by AmaanSayyad** [Suryansh1720001/Flag-Quiz#9]
Spelling Errors, Grammatical Correction, Easy to understand language Implementation.

**Comment by Suryansh1720001** [comment]
Provide the description (which type of correction) !!

**Comment by AmaanSayyad** [comment]
> Provide the description (which type of correction) !!

Provided

**Comment by AmaanSayyad** [comment]
> Provide the description (which type of correction) !!

For more details regarding the correction check the pull request #8
